all: pinvgrd poutgrd srchwave589.JdF.nophase2.iarea

pinvgrd:pinvgrd.f 
	gfortran pinvgrd.f -o pinvgrd

poutgrd:poutgrd.f
	gfortran poutgrd.f -o poutgrd

srchwave589.JdF.nophase2.iarea:srchwave589.JdF.nophase2.iarea.jbr.f
	gfortran srchwave589.JdF.nophase2.iarea.jbr.f -o srchwave589.JdF.nophase2.iarea

